permalink: /:year:month:day/:title
url: https://doc.fadian.me
baseurl: /project

# variables
name: 发电姬OS - doc
description: 发电姬OS - doc
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true
